import Image from 'next/image'
import Link from 'next/link'
import {
  Sparkles,
  CalendarDays,
  Brain,
  Leaf,
  DollarSign,
  Clock,
  Utensils,
  Recycle,
  ArrowRight,
  CheckCircle2,
} from 'lucide-react'
import { Container } from './shared/Container'
import { FadeIn } from './shared/FadeIn'

const autopilotFeatures = [
  {
    icon: Brain,
    title: 'Learns your household',
    body: 'Dietary needs, dislikes, skill level, and household size shape every suggestion.',
  },
  {
    icon: Recycle,
    title: 'Uses your leftovers first',
    body: 'Expiring food gets repurposed into creative dinners — less waste, more flavor.',
  },
  {
    icon: DollarSign,
    title: 'Respects your budget',
    body: 'Stays within your weekly limit. Strict mode never exceeds the per-day cap.',
  },
  {
    icon: Leaf,
    title: 'Seasonal intelligence',
    body: 'Hearty stews in winter, fresh grilling in summer — meals match the season.',
  },
  {
    icon: Clock,
    title: 'Weekday-smart prep times',
    body: 'Quick meals Mon–Thu, more involved recipes on weekends when you have time.',
  },
  {
    icon: Utensils,
    title: 'Cuisine rotation',
    body: 'Never the same cuisine twice in a row. Italian → Mexican → Asian → variety.',
  },
]

const demoWeek = [
  { day: 'Mon', meal: 'Lemon Herb Chicken', time: '25m', tag: 'Mediterranean' },
  { day: 'Tue', meal: 'Black Bean Tacos', time: '20m', tag: 'Mexican' },
  { day: 'Wed', meal: 'Teriyaki Salmon Bowl', time: '30m', tag: 'Japanese' },
  { day: 'Thu', meal: 'One-Pot Pasta Primavera', time: '22m', tag: 'Italian' },
  { day: 'Fri', meal: 'Thai Basil Chicken', time: '35m', tag: 'Thai' },
  { day: 'Sat', meal: 'Slow-Braised Short Ribs', time: '55m', tag: 'American' },
  { day: 'Sun', meal: 'Mushroom Risotto', time: '45m', tag: 'Italian' },
]

const smartSignals = [
  '✓ 5 unique proteins across the week',
  '✓ 3 pantry items already owned',
  '✓ 1 leftover repurposed (roast chicken → tacos)',
  '✓ $62 estimated — $18 under budget',
  '✓ Avg 30 min cook time',
  '✓ 6 different cuisines',
]

export function AutopilotSection() {
  return (
    <section
      className="relative overflow-hidden bg-[#FDF6F1] dark:bg-neutral-950 py-20 md:py-28"
      aria-labelledby="autopilot-heading"
    >
      {/* Subtle background pattern */}
      <div className="absolute inset-0 opacity-[0.03] dark:opacity-[0.02]">
        <div className="absolute inset-0" style={{
          backgroundImage: 'radial-gradient(circle at 1px 1px, currentColor 1px, transparent 0)',
          backgroundSize: '32px 32px',
        }} />
      </div>

      <Container className="relative z-10">
        {/* Header */}
        <FadeIn>
          <div className="mx-auto max-w-3xl text-center">
            <div className="inline-flex items-center gap-2 rounded-full bg-[#D97757]/10 px-4 py-1.5 text-sm font-semibold text-[#D97757] ring-1 ring-[#D97757]/20">
              <Sparkles className="w-4 h-4" />
              AI Autopilot
            </div>
            <h2
              id="autopilot-heading"
              className="mt-5 font-serif text-4xl font-bold tracking-tight text-neutral-900 dark:text-white md:text-5xl"
            >
              One tap. Seven dinners.
              <br />
              <span className="text-[#D97757]">Personalized to your life.</span>
            </h2>
            <p className="mt-5 text-lg leading-relaxed text-neutral-600 dark:text-neutral-300">
              MealEase Autopilot reads your pantry, leftovers, budget, dietary needs, and the season —
              then generates a full week of dinners in seconds. Lock favorites, swap anything, run it again.
            </p>
          </div>
        </FadeIn>

        {/* Demo week preview */}
        <FadeIn delay={0.1}>
          <div className="mt-14 mx-auto max-w-4xl">
            <div className="relative rounded-3xl bg-white dark:bg-neutral-900 ring-1 ring-neutral-200/80 dark:ring-neutral-800 shadow-xl shadow-neutral-200/40 dark:shadow-black/30 overflow-hidden">
              {/* Header bar */}
              <div className="flex items-center justify-between px-5 py-3 border-b border-neutral-100 dark:border-neutral-800">
                <div className="flex items-center gap-2">
                  <CalendarDays className="w-4 h-4 text-[#D97757]" />
                  <span className="text-sm font-semibold text-neutral-900 dark:text-white">This Week&apos;s Plan</span>
                </div>
                <span className="text-xs text-neutral-500 bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-400 px-2 py-0.5 rounded-full font-medium">
                  Generated by Autopilot
                </span>
              </div>

              {/* Week grid */}
              <div className="grid grid-cols-7 divide-x divide-neutral-100 dark:divide-neutral-800">
                {demoWeek.map((day, i) => (
                  <div
                    key={day.day}
                    className="p-3 md:p-4 flex flex-col gap-2 min-h-[140px]"
                  >
                    <span className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">
                      {day.day}
                    </span>
                    <p className="text-xs font-semibold text-neutral-900 dark:text-white leading-tight">
                      {day.meal}
                    </p>
                    <div className="mt-auto flex flex-col gap-1">
                      <span className="text-[10px] text-neutral-500 flex items-center gap-0.5">
                        <Clock className="w-2.5 h-2.5" /> {day.time}
                      </span>
                      <span className="text-[10px] text-[#D97757] font-medium">
                        {day.tag}
                      </span>
                    </div>
                  </div>
                ))}
              </div>

              {/* Smart signals bar */}
              <div className="px-5 py-3 bg-neutral-50 dark:bg-neutral-800/50 border-t border-neutral-100 dark:border-neutral-800">
                <div className="flex flex-wrap gap-x-4 gap-y-1">
                  {smartSignals.slice(0, 4).map((signal) => (
                    <span key={signal} className="text-[11px] text-neutral-600 dark:text-neutral-400">
                      {signal}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </FadeIn>

        {/* Feature grid */}
        <div className="mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {autopilotFeatures.map((feature, i) => {
            const Icon = feature.icon
            return (
              <FadeIn key={feature.title} delay={0.05 * i}>
                <article className="group h-full rounded-2xl bg-white dark:bg-neutral-900 ring-1 ring-neutral-200/70 dark:ring-neutral-800 p-5 hover:ring-[#D97757]/30 hover:shadow-lg transition-all duration-300">
                  <div className="flex items-center gap-3">
                    <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-[#D97757]/10 text-[#D97757] group-hover:bg-[#D97757] group-hover:text-white transition-colors">
                      <Icon className="h-5 w-5" aria-hidden />
                    </span>
                    <h3 className="text-sm font-semibold text-neutral-900 dark:text-white">
                      {feature.title}
                    </h3>
                  </div>
                  <p className="mt-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-400">
                    {feature.body}
                  </p>
                </article>
              </FadeIn>
            )
          })}
        </div>

        {/* How it works mini-flow */}
        <FadeIn delay={0.2}>
          <div className="mt-16 mx-auto max-w-3xl">
            <div className="relative rounded-3xl overflow-hidden">
              <Image
                src="/landing/family-dinner.jpg"
                alt="Family enjoying a meal planned by MealEase Autopilot"
                fill
                sizes="(min-width: 768px) 768px, 100vw"
                className="object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-r from-neutral-950/85 via-neutral-950/70 to-neutral-950/50" />

              <div className="relative z-10 p-8 md:p-12">
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#F3B18E]">
                  How Autopilot works
                </p>
                <h3 className="mt-3 font-serif text-2xl font-bold text-white md:text-3xl">
                  Three signals. One perfect plan.
                </h3>

                <div className="mt-6 grid gap-4 sm:grid-cols-3">
                  {[
                    { step: '01', title: 'Your context', desc: 'Pantry, leftovers, budget, dietary needs, season' },
                    { step: '02', title: 'AI planning', desc: 'Variety, prep-time rules, cuisine rotation, protein spread' },
                    { step: '03', title: 'Your control', desc: 'Lock favorites, swap any day, adjust preferences' },
                  ].map((item) => (
                    <div key={item.step} className="rounded-xl bg-white/10 backdrop-blur-sm ring-1 ring-white/10 p-4">
                      <p className="text-xs font-bold text-[#F3B18E]">{item.step}</p>
                      <p className="mt-1.5 text-sm font-semibold text-white">{item.title}</p>
                      <p className="mt-1 text-xs text-neutral-300 leading-relaxed">{item.desc}</p>
                    </div>
                  ))}
                </div>

                <div className="mt-8 flex flex-col sm:flex-row items-start sm:items-center gap-4">
                  <Link
                    href="/signup"
                    className="inline-flex items-center gap-2 rounded-full bg-[#D97757] hover:bg-[#C86646] text-white font-medium px-6 py-3 transition-colors shadow-lg shadow-[#D97757]/20"
                  >
                    <Sparkles className="w-4 h-4" />
                    Try Autopilot free
                    <ArrowRight className="w-4 h-4" />
                  </Link>
                  <p className="text-xs text-neutral-400">
                    No credit card required · 3 free plans per week
                  </p>
                </div>
              </div>
            </div>
          </div>
        </FadeIn>
      </Container>
    </section>
  )
}
